PostHog/posthog-flutter

pubspec.yaml

Required by dart publish in new version of flutter

Set flutter version in pubspec.yaml

---

example/lib/generated_plugin_registrant.dart

fix posthog web import

---

CHANGELOG.md
pubspec.yaml

Bump version to 2.0.3 for bugfixes

Bump version to 2.0.3

---

.github/workflows/publish.yml

feat: add ci for pushing to pub.dev automagically

---

.github/workflows/ci.yml
.github/workflows/test.yml
.gitignore
example/android/build.gradle
example/ios/Flutter/AppFrameworkInfo.plist
example/ios/Podfile
example/ios/Podfile.lock
example/ios/Runner.xcodeproj/project.pbxproj
example/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
example/ios/Runner/Info.plist
ios/Classes/PosthogFlutterPlugin.m

The recently added Feature flags support had a bug.
Closes https://github.com/PostHog/posthog-flutter/issues/33
Closes https://github.com/PostHog/posthog-flutter/issues/31
* Fixes the bug
* Adds a CI workflow for building the example repo to at least check that everything is correct

fix: iOS build issue

---

.github/workflows/publish.yml
RELEASING.md

https://dart.dev/tools/pub/automated-publishing#publishing-packages-using-github-actions

Update release actions

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/ISSUE_TEMPLATE/maintainer-blank.yml
.github/dependabot.yml
.github/pull_request_template.md

Better templates and codeowner so I automatically get assigned + we force people to think about before opening issues/PRs with very good steps and/or explanations.

Add GH templates and codeowner

---

lib/posthog_flutter.dart
lib/posthog_flutter_web.dart
lib/src/posthog.dart
lib/src/posthog_flutter_io.dart
lib/src/posthog_flutter_platform_interface.dart
lib/src/posthog_flutter_web_handler.dart
lib/src/posthog_observer.dart

* Moved non-exported classes to the src folder
* Imports are relative instead of packages, see [recommendation](https://dart.dev/effective-dart/usage#prefer-relative-import-paths)
Will cut v4 preview after this PR
_#skip-changelog_

ref: relative imports and moved non exported files to src folder

---

android/build.gradle

chore: upgrade android sdk to 3.1.1

---

README.md

chore: community page

---

CHANGELOG.md
RELEASING.md
example/lib/main.dart
ios/posthog_flutter.podspec

Going to cut a 4.0.0-RC.1 next

chore: upgrade iOS SDK to v3.0.0

---

CHANGELOG.md
android/build.gradle
ios/posthog_flutter.podspec

Closes https://github.com/PostHog/posthog-flutter/issues/50

chore: Upgrade iOS SDK to 3.1.0

---

CHANGELOG.md
ios/Resources/PrivacyInfo.xcprivacy
ios/posthog_flutter.podspec

Closes https://github.com/PostHog/posthog-flutter/issues/93

add PrivacyInfo

---

CHANGELOG.md
macos/Resources/PrivacyInfo.xcprivacy

Tries to fix https://github.com/PostHog/posthog-flutter/issues/104

fix: privacy info file for macos

---

example/lib/main.dart

fix: example routing

---

CHANGELOG.md
lib/posthog_flutter.dart
lib/posthog_flutter_web.dart
lib/src/posthog_flutter_web_handler.dart
lib/src/posthog_widget.dart
lib/src/posthog_widget_widget.dart
lib/src/replay/screenshot/screenshot_capturer.dart
lib/src/replay/screenshot/snapshot_manager.dart

Relates to https://github.com/PostHog/posthog-flutter/issues/142

fix: dispose recorder if masking is disabled

---

example/lib/main.dart
example/web/index.html

chore: upgrade flutter web example

---

CHANGELOG.md
lib/src/posthog_flutter_io.dart
pubspec.yaml

https://github.com/PostHog/posthog-flutter/issues/51#issuecomment-2770630838

chore: windows and linux noop

---

CHANGELOG.md
lib/src/replay/element_parsers/element_data_factory.dart
lib/src/replay/element_parsers/element_parser.dart
lib/src/replay/element_parsers/image_element/render_image_parser.dart
lib/src/replay/image_extension.dart
lib/src/replay/screenshot/screenshot_capturer.dart
lib/src/replay/size_extension.dart

https://x.com/filippkowalski/status/1909872437006659795

fix: check if image size is valid before sending snapshot

---

lib/src/posthog_flutter_web_handler.dart

- Make contributions accessible to all engineers.
_#skip-changelog_
Nope 🌝

docs: Translate comments to English
